### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Sieglinde-IBM** [qiskit-community/Quantum-Challenge-Grader#168]
@vabarbosa not sure if you are the right person to flag, but I could see you made the last commit.

This readme mentioned the Quantum Lab which has been sunset. Can you remove mention of it.

Also, can you provide more information for step 2. Configure the following environment variables, it looks like there is a link missing.

**Comment by vabarbosa** [comment]
thank you @Sieglinde-IBM 
README has been updated
